name = "Synixe"
prefix = "synixe"
mainprefix = "x"
author = "Synixe Contractors"

[files]
include = [
    "synixe_x64.dll",
]

[hemtt.launch.default]
workshop = [
    "450814997", # CBA
    "463939057", # ACE3
    "1779063631", # Zeus Enhanced
    "2975055854", # Secondary Mk13
    "751965892", # ACRE2
    "623475643", # 3den Enhanced
]
dlc = [
    "ws",
    "rf",
]

[hemtt.launch.cup_terrains_core]
extends = "default"
workshop = [
    "583496184", # CUP Terrains - Core
]

[hemtt.launch.aegis]
extends = "default"
workshop = [
    "2538332070", # Aegis - Development
    "2538339575", # Atlas - Development
    "2538342230", # Opposing Forces - Development
    "2402219547", # Theseus
    "2684335735", # Revoluci√≥n
    "3302425224", # JCA MP5
]

[hemtt.launch.mgp]
extends = "default"
workshop = [
    "2871002081" # Mil Gear Pack - Simpel
]

[hemtt.launch.adt]
extends = "default"
workshop = [
    "3499977893", # ADT
]

[hemtt.launch.oteden]
extends = "default"
workshop = [
    "1923321700", # O&T Expansion Eden
]

[hemtt.launch.sma]
extends = "default"
workshop = [
    "2983059191", # SMA Optics
]

[hemtt.launch.theseus]
extends = "default"
workshop = [
    "646999497" # Theseus Services
]

[hemtt.launch.archipelago]
extends = "default"
workshop = [
    "1726184748", # Archipelago
]

[hemtt.launch.north_takistan]
extends = "cup_terrains_core"
workshop = [
    "2829330653", # North Takistan
]
